### ISSUE TITLE
Connection delay in time-dependent routing

### ISSUE THREAD

**Issue by jaauld14** [anl-tracc/polaris#11]
Question about function:

cost_between(typename MT::time_dependent_edge....) Routable_Agent_Implementation line 63

The connection cost does not seem to be included in the return value, as it is in the static case.  Is the connection specific cost accounted for in the LinkMOE read from the results database?  This value seems to be link specific instead of turn movement specific.

**Comment by MichaelHope** [comment]
Is this still an open question?

**Comment by jaauld14** [comment]
Yes, I am still unclear on what LinkMOE is being produced for turns vs links, and how it is used internally in the time-dependent router.  If you have time to look it over some time in the future it would be helpful.

**Comment by jaauld14** [comment]
The historical connection cost issue has been resolved with revision 9eeebfe9e5db2a93b2d921fde59a001cbe66b366 (11/10/15).
