### ISSUE TITLE
Master: database schema error

### ISSUE THREAD

**Issue by jaauld14** [anl-tracc/polaris#29]
The ODB compiler is not creating schemas for some of the databases (example: PopSyn and Result for the Population_Synthesizer build).  An exception is thrown when trying to use the create_sqlite_database(name,schema) function, when the schemas do not exist.

**Comment by VadimSokolov** [comment]
Seems like the things are properly created. I will need to look at your code to see how you use it.

**Comment by jaauld14** [comment]
i'll see if i can recreate the error in simplified code.
